#!/bin/bash

dir="$1"

# No directory has been provided, use current
if [ -z "$dir" ]
then
    dir="`pwd`"
fi

# Make sure directory ends with "/"
if [[ $dir != */ ]]
then
	dir="$dir/*"
else
	dir="$dir*"
fi

echo "Directory is: [$dir]"

# Loop all sub-directories


check_git_status(){
    
    echo -en "\033[0;35m"
    echo "$1"
    echo -en "\033[0m"

    mod=0
    cd $1

    # Check branch
    git status | head -n1



    # Check for modified files
    if [ $(git status | grep modified -c) -ne 0 ]
    then
	    mod=1
	    echo -e "\e[45m"
	    echo -e "\033[41mModified files\e[0m"
    fi

    # Check for untracked files
    if [ $(git status | grep Untracked -c) -ne 0 ]
    then
	    mod=1
	    
	    echo -e "\e[41m"
	    echo -e "\033[44mUntracked files\e[0m"
        
    fi

    # Check for pending push
    if [ $(git status | grep 'publish your local' -c) -ne 0 ]
    then
        mod=1

        echo -e "\e[41m"
        echo -e "\033[45mCommits done but push pending\e[0m"

    fi


    # Check if everything is peachy keen
    if [ $mod -eq 0 ]
    then
	    echo "Nothing to commit"
    fi

    cd ../

    echo
}

check_svn_status(){
    
    echo -en "\033[0;35m"
    echo "$1"
    echo -en "\033[0m"
    cd $1

    if [ $(svn status | grep M -c) -ne 0 ]
    then
        mod=1
        echo -e "\e[45m"
        echo -e "\033[41mSVN: Modified files\e[0m"
    fi
    
    # Check for untracked files
    if [ $(svn status | grep ? -c) -ne 0 ]
    then
	    mod=1
	    echo -e "\e[41m"
	    echo -e "\033[44mSVN: Untracked files\e[0m"
        
    fi
    
    if [ $mod -eq 0 ]
    then
        echo "Nothing to commit"
    fi
    cd ../
    
    echo
}

level=3


check_status_recursive()
{
    if [ "$2" -eq "$level" ] 
    then
        return
    fi
    
    #echo "Level: $2" 
           
    #echo -e "\e[1;33m$1 is not a git or svn repository \e[0m"
    
    subdir="$1/*"
    for f1 in $subdir
    do
        # Only interested in directories
        [ -d "${f1}" ] || continue
        # Check if directory is a git repository
        if [ -d "$f1/.git" ]
        then
            check_git_status $f1
        elif [ -d "$f1/.svn" ]
        then
            check_svn_status $f1
        elif [ -d "$f1/.dropbox.cache" ]
        then
            continue
        else
            #echo "No Git repository at Level $2 ($f1). Going one level deeper"
            newLevel="$(($2+1))"
            check_status_recursive $f1 $newLevel
            
        fi
    done   
}


for f in $dir
do
	# Only interested in directories
	[ -d "${f}" ] || continue

	# Check if directory is a git repository
	if [ -d "$f/.git" ]
	then

        check_git_status $f
    elif [ -d "$f/.svn" ]
    then
        check_svn_status $f
    elif [ -d "$f/.dropbox.cache" ]
    then
        continue    
    else
        current_level=0
        check_status_recursive $f $current_level
	fi

done
